/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public final class AlphaBlendType {
  public final static AlphaBlendType Opacity = new AlphaBlendType("Opacity", GDXJNI.AlphaBlendType_Opacity_get());
  public final static AlphaBlendType Blend = new AlphaBlendType("Blend", GDXJNI.AlphaBlendType_Blend_get());
  public final static AlphaBlendType Add = new AlphaBlendType("Add", GDXJNI.AlphaBlendType_Add_get());
  public final static AlphaBlendType Sub = new AlphaBlendType("Sub", GDXJNI.AlphaBlendType_Sub_get());
  public final static AlphaBlendType Mul = new AlphaBlendType("Mul", GDXJNI.AlphaBlendType_Mul_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static AlphaBlendType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + AlphaBlendType.class + " with value " + swigValue);
  }

  private AlphaBlendType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private AlphaBlendType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private AlphaBlendType(String swigName, AlphaBlendType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static AlphaBlendType[] swigValues = { Opacity, Blend, Add, Sub, Mul };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

