/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class ArrayTextureIndexes {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ArrayTextureIndexes(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ArrayTextureIndexes obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_ArrayTextureIndexes(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArrayTextureIndexes() {
    this(GDXJNI.new_ArrayTextureIndexes__SWIG_0(), true);
  }

  public ArrayTextureIndexes(ArrayTextureIndexes other) {
    this(GDXJNI.new_ArrayTextureIndexes__SWIG_1(ArrayTextureIndexes.getCPtr(other), other), true);
  }

  public long size() {
    return GDXJNI.ArrayTextureIndexes_size(swigCPtr, this);
  }

  public boolean isEmpty() {
    return GDXJNI.ArrayTextureIndexes_isEmpty(swigCPtr, this);
  }

  public void fill(int u) {
    GDXJNI.ArrayTextureIndexes_fill(swigCPtr, this, u);
  }

  public int get(int i) {
    return GDXJNI.ArrayTextureIndexes_get(swigCPtr, this, i);
  }

  public void set(int i, int val) {
    GDXJNI.ArrayTextureIndexes_set(swigCPtr, this, i, val);
  }

}
