/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class ArrayTextureFilters {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ArrayTextureFilters(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ArrayTextureFilters obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_ArrayTextureFilters(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArrayTextureFilters() {
    this(GDXJNI.new_ArrayTextureFilters__SWIG_0(), true);
  }

  public ArrayTextureFilters(ArrayTextureFilters other) {
    this(GDXJNI.new_ArrayTextureFilters__SWIG_1(ArrayTextureFilters.getCPtr(other), other), true);
  }

  public long size() {
    return GDXJNI.ArrayTextureFilters_size(swigCPtr, this);
  }

  public boolean isEmpty() {
    return GDXJNI.ArrayTextureFilters_isEmpty(swigCPtr, this);
  }

  public void fill(TextureFilterType u) {
    GDXJNI.ArrayTextureFilters_fill(swigCPtr, this, u.swigValue());
  }

  public TextureFilterType get(int i) {
    return TextureFilterType.swigToEnum(GDXJNI.ArrayTextureFilters_get(swigCPtr, this, i));
  }

  public void set(int i, TextureFilterType val) {
    GDXJNI.ArrayTextureFilters_set(swigCPtr, this, i, val.swigValue());
  }

}
