/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class ArrayTextureWraps {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ArrayTextureWraps(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ArrayTextureWraps obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_ArrayTextureWraps(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArrayTextureWraps() {
    this(GDXJNI.new_ArrayTextureWraps__SWIG_0(), true);
  }

  public ArrayTextureWraps(ArrayTextureWraps other) {
    this(GDXJNI.new_ArrayTextureWraps__SWIG_1(ArrayTextureWraps.getCPtr(other), other), true);
  }

  public long size() {
    return GDXJNI.ArrayTextureWraps_size(swigCPtr, this);
  }

  public boolean isEmpty() {
    return GDXJNI.ArrayTextureWraps_isEmpty(swigCPtr, this);
  }

  public void fill(TextureWrapType u) {
    GDXJNI.ArrayTextureWraps_fill(swigCPtr, this, u.swigValue());
  }

  public TextureWrapType get(int i) {
    return TextureWrapType.swigToEnum(GDXJNI.ArrayTextureWraps_get(swigCPtr, this, i));
  }

  public void set(int i, TextureWrapType val) {
    GDXJNI.ArrayTextureWraps_set(swigCPtr, this, i, val.swigValue());
  }

}
