/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public final class BillboardType {
  public final static BillboardType Billboard = new BillboardType("Billboard", GDXJNI.BillboardType_Billboard_get());
  public final static BillboardType YAxisFixed = new BillboardType("YAxisFixed", GDXJNI.BillboardType_YAxisFixed_get());
  public final static BillboardType Fixed = new BillboardType("Fixed", GDXJNI.BillboardType_Fixed_get());
  public final static BillboardType RotatedBillboard = new BillboardType("RotatedBillboard", GDXJNI.BillboardType_RotatedBillboard_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static BillboardType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + BillboardType.class + " with value " + swigValue);
  }

  private BillboardType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private BillboardType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private BillboardType(String swigName, BillboardType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static BillboardType[] swigValues = { Billboard, YAxisFixed, Fixed, RotatedBillboard };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

