/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class Color {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Color(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Color obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_Color(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setR(short value) {
    GDXJNI.Color_r_set(swigCPtr, this, value);
  }

  public short getR() {
    return GDXJNI.Color_r_get(swigCPtr, this);
  }

  public void setG(short value) {
    GDXJNI.Color_g_set(swigCPtr, this, value);
  }

  public short getG() {
    return GDXJNI.Color_g_get(swigCPtr, this);
  }

  public void setB(short value) {
    GDXJNI.Color_b_set(swigCPtr, this, value);
  }

  public short getB() {
    return GDXJNI.Color_b_get(swigCPtr, this);
  }

  public void setA(short value) {
    GDXJNI.Color_a_set(swigCPtr, this, value);
  }

  public short getA() {
    return GDXJNI.Color_a_get(swigCPtr, this);
  }

  public Color() {
    this(GDXJNI.new_Color__SWIG_0(), true);
  }

  public Color(short r, short g, short b, short a) {
    this(GDXJNI.new_Color__SWIG_1(r, g, b, a), true);
  }

  public Color(short r, short g, short b) {
    this(GDXJNI.new_Color__SWIG_2(r, g, b), true);
  }

}
