/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public final class CullingType {
  public final static CullingType Front = new CullingType("Front", GDXJNI.CullingType_Front_get());
  public final static CullingType Back = new CullingType("Back", GDXJNI.CullingType_Back_get());
  public final static CullingType Double = new CullingType("Double", GDXJNI.CullingType_Double_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CullingType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CullingType.class + " with value " + swigValue);
  }

  private CullingType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CullingType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CullingType(String swigName, CullingType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CullingType[] swigValues = { Front, Back, Double };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

