/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public final class Easing3Type {
  public final static Easing3Type StartEndSpeed = new Easing3Type("StartEndSpeed", GDXJNI.Easing3Type_StartEndSpeed_get());
  public final static Easing3Type Linear = new Easing3Type("Linear", GDXJNI.Easing3Type_Linear_get());
  public final static Easing3Type EaseInQuadratic = new Easing3Type("EaseInQuadratic", GDXJNI.Easing3Type_EaseInQuadratic_get());
  public final static Easing3Type EaseOutQuadratic = new Easing3Type("EaseOutQuadratic", GDXJNI.Easing3Type_EaseOutQuadratic_get());
  public final static Easing3Type EaseInOutQuadratic = new Easing3Type("EaseInOutQuadratic", GDXJNI.Easing3Type_EaseInOutQuadratic_get());
  public final static Easing3Type EaseInCubic = new Easing3Type("EaseInCubic", GDXJNI.Easing3Type_EaseInCubic_get());
  public final static Easing3Type EaseOutCubic = new Easing3Type("EaseOutCubic", GDXJNI.Easing3Type_EaseOutCubic_get());
  public final static Easing3Type EaseInOutCubic = new Easing3Type("EaseInOutCubic", GDXJNI.Easing3Type_EaseInOutCubic_get());
  public final static Easing3Type EaseInQuartic = new Easing3Type("EaseInQuartic", GDXJNI.Easing3Type_EaseInQuartic_get());
  public final static Easing3Type EaseOutQuartic = new Easing3Type("EaseOutQuartic", GDXJNI.Easing3Type_EaseOutQuartic_get());
  public final static Easing3Type EaseInOutQuartic = new Easing3Type("EaseInOutQuartic", GDXJNI.Easing3Type_EaseInOutQuartic_get());
  public final static Easing3Type EaseInQuintic = new Easing3Type("EaseInQuintic", GDXJNI.Easing3Type_EaseInQuintic_get());
  public final static Easing3Type EaseOutQuintic = new Easing3Type("EaseOutQuintic", GDXJNI.Easing3Type_EaseOutQuintic_get());
  public final static Easing3Type EaseInOutQuintic = new Easing3Type("EaseInOutQuintic", GDXJNI.Easing3Type_EaseInOutQuintic_get());
  public final static Easing3Type EaseInBack = new Easing3Type("EaseInBack", GDXJNI.Easing3Type_EaseInBack_get());
  public final static Easing3Type EaseOutBack = new Easing3Type("EaseOutBack", GDXJNI.Easing3Type_EaseOutBack_get());
  public final static Easing3Type EaseInOutBack = new Easing3Type("EaseInOutBack", GDXJNI.Easing3Type_EaseInOutBack_get());
  public final static Easing3Type EaseInBounce = new Easing3Type("EaseInBounce", GDXJNI.Easing3Type_EaseInBounce_get());
  public final static Easing3Type EaseOutBounce = new Easing3Type("EaseOutBounce", GDXJNI.Easing3Type_EaseOutBounce_get());
  public final static Easing3Type EaseInOutBounce = new Easing3Type("EaseInOutBounce", GDXJNI.Easing3Type_EaseInOutBounce_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Easing3Type swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Easing3Type.class + " with value " + swigValue);
  }

  private Easing3Type(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Easing3Type(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Easing3Type(String swigName, Easing3Type swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Easing3Type[] swigValues = { StartEndSpeed, Linear, EaseInQuadratic, EaseOutQuadratic, EaseInOutQuadratic, EaseInCubic, EaseOutCubic, EaseInOutCubic, EaseInQuartic, EaseOutQuartic, EaseInOutQuartic, EaseInQuintic, EaseOutQuintic, EaseInOutQuintic, EaseInBack, EaseOutBack, EaseInOutBack, EaseInBounce, EaseOutBounce, EaseInOutBounce };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

