/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public final class eEffectNodeType {
  public final static eEffectNodeType EFFECT_NODE_TYPE_ROOT = new eEffectNodeType("EFFECT_NODE_TYPE_ROOT", GDXJNI.EFFECT_NODE_TYPE_ROOT_get());
  public final static eEffectNodeType EFFECT_NODE_TYPE_NONE = new eEffectNodeType("EFFECT_NODE_TYPE_NONE", GDXJNI.EFFECT_NODE_TYPE_NONE_get());
  public final static eEffectNodeType EFFECT_NODE_TYPE_SPRITE = new eEffectNodeType("EFFECT_NODE_TYPE_SPRITE", GDXJNI.EFFECT_NODE_TYPE_SPRITE_get());
  public final static eEffectNodeType EFFECT_NODE_TYPE_RIBBON = new eEffectNodeType("EFFECT_NODE_TYPE_RIBBON", GDXJNI.EFFECT_NODE_TYPE_RIBBON_get());
  public final static eEffectNodeType EFFECT_NODE_TYPE_RING = new eEffectNodeType("EFFECT_NODE_TYPE_RING", GDXJNI.EFFECT_NODE_TYPE_RING_get());
  public final static eEffectNodeType EFFECT_NODE_TYPE_MODEL = new eEffectNodeType("EFFECT_NODE_TYPE_MODEL", GDXJNI.EFFECT_NODE_TYPE_MODEL_get());
  public final static eEffectNodeType EFFECT_NODE_TYPE_TRACK = new eEffectNodeType("EFFECT_NODE_TYPE_TRACK", GDXJNI.EFFECT_NODE_TYPE_TRACK_get());
  public final static eEffectNodeType EFFECT_NODE_TYPE_DWORD = new eEffectNodeType("EFFECT_NODE_TYPE_DWORD", GDXJNI.EFFECT_NODE_TYPE_DWORD_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static eEffectNodeType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + eEffectNodeType.class + " with value " + swigValue);
  }

  private eEffectNodeType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private eEffectNodeType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private eEffectNodeType(String swigName, eEffectNodeType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static eEffectNodeType[] swigValues = { EFFECT_NODE_TYPE_ROOT, EFFECT_NODE_TYPE_NONE, EFFECT_NODE_TYPE_SPRITE, EFFECT_NODE_TYPE_RIBBON, EFFECT_NODE_TYPE_RING, EFFECT_NODE_TYPE_MODEL, EFFECT_NODE_TYPE_TRACK, EFFECT_NODE_TYPE_DWORD };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

