/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class EffectNode {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EffectNode(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EffectNode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_EffectNode(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EffekseerEffect GetEffect() {
    long cPtr = GDXJNI.EffectNode_GetEffect(swigCPtr, this);
    return (cPtr == 0) ? null : new EffekseerEffect(cPtr, false);
  }

  public int GetGeneration() {
    return GDXJNI.EffectNode_GetGeneration(swigCPtr, this);
  }

  public int GetChildrenCount() {
    return GDXJNI.EffectNode_GetChildrenCount(swigCPtr, this);
  }

  public EffectNode GetChild(int index) {
    long cPtr = GDXJNI.EffectNode_GetChild(swigCPtr, this, index);
    return (cPtr == 0) ? null : new EffectNode(cPtr, false);
  }

  public EffectBasicRenderParameter GetBasicRenderParameter() {
    return new EffectBasicRenderParameter(GDXJNI.EffectNode_GetBasicRenderParameter(swigCPtr, this), true);
  }

  public void SetBasicRenderParameter(EffectBasicRenderParameter param) {
    GDXJNI.EffectNode_SetBasicRenderParameter(swigCPtr, this, EffectBasicRenderParameter.getCPtr(param), param);
  }

  public EffectModelParameter GetEffectModelParameter() {
    return new EffectModelParameter(GDXJNI.EffectNode_GetEffectModelParameter(swigCPtr, this), true);
  }

  public EffectInstanceTerm CalculateInstanceTerm(EffectInstanceTerm parentTerm) {
    return new EffectInstanceTerm(GDXJNI.EffectNode_CalculateInstanceTerm(swigCPtr, this, EffectInstanceTerm.getCPtr(parentTerm), parentTerm), true);
  }

}
