/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class EffectTerm {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EffectTerm(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EffectTerm obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_EffectTerm(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTermMin(int value) {
    GDXJNI.EffectTerm_TermMin_set(swigCPtr, this, value);
  }

  public int getTermMin() {
    return GDXJNI.EffectTerm_TermMin_get(swigCPtr, this);
  }

  public void setTermMax(int value) {
    GDXJNI.EffectTerm_TermMax_set(swigCPtr, this, value);
  }

  public int getTermMax() {
    return GDXJNI.EffectTerm_TermMax_get(swigCPtr, this);
  }

  public EffectTerm() {
    this(GDXJNI.new_EffectTerm(), true);
  }

}
