/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class EffectInstanceTerm {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EffectInstanceTerm(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EffectInstanceTerm obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_EffectInstanceTerm(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFirstInstanceStartMin(int value) {
    GDXJNI.EffectInstanceTerm_FirstInstanceStartMin_set(swigCPtr, this, value);
  }

  public int getFirstInstanceStartMin() {
    return GDXJNI.EffectInstanceTerm_FirstInstanceStartMin_get(swigCPtr, this);
  }

  public void setFirstInstanceStartMax(int value) {
    GDXJNI.EffectInstanceTerm_FirstInstanceStartMax_set(swigCPtr, this, value);
  }

  public int getFirstInstanceStartMax() {
    return GDXJNI.EffectInstanceTerm_FirstInstanceStartMax_get(swigCPtr, this);
  }

  public void setFirstInstanceEndMin(int value) {
    GDXJNI.EffectInstanceTerm_FirstInstanceEndMin_set(swigCPtr, this, value);
  }

  public int getFirstInstanceEndMin() {
    return GDXJNI.EffectInstanceTerm_FirstInstanceEndMin_get(swigCPtr, this);
  }

  public void setFirstInstanceEndMax(int value) {
    GDXJNI.EffectInstanceTerm_FirstInstanceEndMax_set(swigCPtr, this, value);
  }

  public int getFirstInstanceEndMax() {
    return GDXJNI.EffectInstanceTerm_FirstInstanceEndMax_get(swigCPtr, this);
  }

  public void setLastInstanceStartMin(int value) {
    GDXJNI.EffectInstanceTerm_LastInstanceStartMin_set(swigCPtr, this, value);
  }

  public int getLastInstanceStartMin() {
    return GDXJNI.EffectInstanceTerm_LastInstanceStartMin_get(swigCPtr, this);
  }

  public void setLastInstanceStartMax(int value) {
    GDXJNI.EffectInstanceTerm_LastInstanceStartMax_set(swigCPtr, this, value);
  }

  public int getLastInstanceStartMax() {
    return GDXJNI.EffectInstanceTerm_LastInstanceStartMax_get(swigCPtr, this);
  }

  public void setLastInstanceEndMin(int value) {
    GDXJNI.EffectInstanceTerm_LastInstanceEndMin_set(swigCPtr, this, value);
  }

  public int getLastInstanceEndMin() {
    return GDXJNI.EffectInstanceTerm_LastInstanceEndMin_get(swigCPtr, this);
  }

  public void setLastInstanceEndMax(int value) {
    GDXJNI.EffectInstanceTerm_LastInstanceEndMax_set(swigCPtr, this, value);
  }

  public int getLastInstanceEndMax() {
    return GDXJNI.EffectInstanceTerm_LastInstanceEndMax_get(swigCPtr, this);
  }

  public EffectInstanceTerm() {
    this(GDXJNI.new_EffectInstanceTerm(), true);
  }

}
