/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public final class eRenderingOrder {
  public final static eRenderingOrder RenderingOrder_FirstCreatedInstanceIsFirst = new eRenderingOrder("RenderingOrder_FirstCreatedInstanceIsFirst", GDXJNI.RenderingOrder_FirstCreatedInstanceIsFirst_get());
  public final static eRenderingOrder RenderingOrder_FirstCreatedInstanceIsLast = new eRenderingOrder("RenderingOrder_FirstCreatedInstanceIsLast", GDXJNI.RenderingOrder_FirstCreatedInstanceIsLast_get());
  public final static eRenderingOrder RenderingOrder_DWORD = new eRenderingOrder("RenderingOrder_DWORD", GDXJNI.RenderingOrder_DWORD_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static eRenderingOrder swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + eRenderingOrder.class + " with value " + swigValue);
  }

  private eRenderingOrder(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private eRenderingOrder(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private eRenderingOrder(String swigName, eRenderingOrder swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static eRenderingOrder[] swigValues = { RenderingOrder_FirstCreatedInstanceIsFirst, RenderingOrder_FirstCreatedInstanceIsLast, RenderingOrder_DWORD };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

