/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class FCurveVectorColor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FCurveVectorColor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FCurveVectorColor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_FCurveVectorColor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTimeline(FCurveTimelineType value) {
    GDXJNI.FCurveVectorColor_Timeline_set(swigCPtr, this, value.swigValue());
  }

  public FCurveTimelineType getTimeline() {
    return FCurveTimelineType.swigToEnum(GDXJNI.FCurveVectorColor_Timeline_get(swigCPtr, this));
  }

  public void setR(FCurve value) {
    GDXJNI.FCurveVectorColor_R_set(swigCPtr, this, FCurve.getCPtr(value), value);
  }

  public FCurve getR() {
    long cPtr = GDXJNI.FCurveVectorColor_R_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FCurve(cPtr, false);
  }

  public void setG(FCurve value) {
    GDXJNI.FCurveVectorColor_G_set(swigCPtr, this, FCurve.getCPtr(value), value);
  }

  public FCurve getG() {
    long cPtr = GDXJNI.FCurveVectorColor_G_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FCurve(cPtr, false);
  }

  public void setB(FCurve value) {
    GDXJNI.FCurveVectorColor_B_set(swigCPtr, this, FCurve.getCPtr(value), value);
  }

  public FCurve getB() {
    long cPtr = GDXJNI.FCurveVectorColor_B_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FCurve(cPtr, false);
  }

  public void setA(FCurve value) {
    GDXJNI.FCurveVectorColor_A_set(swigCPtr, this, FCurve.getCPtr(value), value);
  }

  public FCurve getA() {
    long cPtr = GDXJNI.FCurveVectorColor_A_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FCurve(cPtr, false);
  }

  public FCurveVectorColor() {
    this(GDXJNI.new_FCurveVectorColor(), true);
  }

}
