/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class FCurveVector3D {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FCurveVector3D(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FCurveVector3D obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_FCurveVector3D(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTimeline(FCurveTimelineType value) {
    GDXJNI.FCurveVector3D_Timeline_set(swigCPtr, this, value.swigValue());
  }

  public FCurveTimelineType getTimeline() {
    return FCurveTimelineType.swigToEnum(GDXJNI.FCurveVector3D_Timeline_get(swigCPtr, this));
  }

  public void setX(FCurve value) {
    GDXJNI.FCurveVector3D_X_set(swigCPtr, this, FCurve.getCPtr(value), value);
  }

  public FCurve getX() {
    long cPtr = GDXJNI.FCurveVector3D_X_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FCurve(cPtr, false);
  }

  public void setY(FCurve value) {
    GDXJNI.FCurveVector3D_Y_set(swigCPtr, this, FCurve.getCPtr(value), value);
  }

  public FCurve getY() {
    long cPtr = GDXJNI.FCurveVector3D_Y_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FCurve(cPtr, false);
  }

  public void setZ(FCurve value) {
    GDXJNI.FCurveVector3D_Z_set(swigCPtr, this, FCurve.getCPtr(value), value);
  }

  public FCurve getZ() {
    long cPtr = GDXJNI.FCurveVector3D_Z_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FCurve(cPtr, false);
  }

  public FCurveVector3D() {
    this(GDXJNI.new_FCurveVector3D(), true);
  }

}
