/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class ForceFieldFalloffTubeParameter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ForceFieldFalloffTubeParameter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ForceFieldFalloffTubeParameter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_ForceFieldFalloffTubeParameter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRadiusPower(float value) {
    GDXJNI.ForceFieldFalloffTubeParameter_RadiusPower_set(swigCPtr, this, value);
  }

  public float getRadiusPower() {
    return GDXJNI.ForceFieldFalloffTubeParameter_RadiusPower_get(swigCPtr, this);
  }

  public void setMinRadius(float value) {
    GDXJNI.ForceFieldFalloffTubeParameter_MinRadius_set(swigCPtr, this, value);
  }

  public float getMinRadius() {
    return GDXJNI.ForceFieldFalloffTubeParameter_MinRadius_get(swigCPtr, this);
  }

  public void setMaxRadius(float value) {
    GDXJNI.ForceFieldFalloffTubeParameter_MaxRadius_set(swigCPtr, this, value);
  }

  public float getMaxRadius() {
    return GDXJNI.ForceFieldFalloffTubeParameter_MaxRadius_get(swigCPtr, this);
  }

  public ForceFieldFalloffTubeParameter() {
    this(GDXJNI.new_ForceFieldFalloffTubeParameter(), true);
  }

}
