/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public final class ForceFieldVortexType {
  public final static ForceFieldVortexType ConstantAngle = new ForceFieldVortexType("ConstantAngle", GDXJNI.ForceFieldVortexType_ConstantAngle_get());
  public final static ForceFieldVortexType ConstantSpeed = new ForceFieldVortexType("ConstantSpeed", GDXJNI.ForceFieldVortexType_ConstantSpeed_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ForceFieldVortexType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ForceFieldVortexType.class + " with value " + swigValue);
  }

  private ForceFieldVortexType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ForceFieldVortexType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ForceFieldVortexType(String swigName, ForceFieldVortexType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ForceFieldVortexType[] swigValues = { ConstantAngle, ConstantSpeed };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

