/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class ForceFieldCommonParameter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ForceFieldCommonParameter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ForceFieldCommonParameter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_ForceFieldCommonParameter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPosition(SIMDVec3f value) {
    GDXJNI.ForceFieldCommonParameter_Position_set(swigCPtr, this, SIMDVec3f.getCPtr(value), value);
  }

  public SIMDVec3f getPosition() {
    long cPtr = GDXJNI.ForceFieldCommonParameter_Position_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SIMDVec3f(cPtr, false);
  }

  public void setPreviousVelocity(SIMDVec3f value) {
    GDXJNI.ForceFieldCommonParameter_PreviousVelocity_set(swigCPtr, this, SIMDVec3f.getCPtr(value), value);
  }

  public SIMDVec3f getPreviousVelocity() {
    long cPtr = GDXJNI.ForceFieldCommonParameter_PreviousVelocity_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SIMDVec3f(cPtr, false);
  }

  public void setPreviousSumVelocity(SIMDVec3f value) {
    GDXJNI.ForceFieldCommonParameter_PreviousSumVelocity_set(swigCPtr, this, SIMDVec3f.getCPtr(value), value);
  }

  public SIMDVec3f getPreviousSumVelocity() {
    long cPtr = GDXJNI.ForceFieldCommonParameter_PreviousSumVelocity_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SIMDVec3f(cPtr, false);
  }

  public void setFieldCenter(SIMDVec3f value) {
    GDXJNI.ForceFieldCommonParameter_FieldCenter_set(swigCPtr, this, SIMDVec3f.getCPtr(value), value);
  }

  public SIMDVec3f getFieldCenter() {
    long cPtr = GDXJNI.ForceFieldCommonParameter_FieldCenter_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SIMDVec3f(cPtr, false);
  }

  public void setTargetPosition(SIMDVec3f value) {
    GDXJNI.ForceFieldCommonParameter_TargetPosition_set(swigCPtr, this, SIMDVec3f.getCPtr(value), value);
  }

  public SIMDVec3f getTargetPosition() {
    long cPtr = GDXJNI.ForceFieldCommonParameter_TargetPosition_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SIMDVec3f(cPtr, false);
  }

  public void setFieldRotation(SIMDMat44f value) {
    GDXJNI.ForceFieldCommonParameter_FieldRotation_set(swigCPtr, this, SIMDMat44f.getCPtr(value), value);
  }

  public SIMDMat44f getFieldRotation() {
    long cPtr = GDXJNI.ForceFieldCommonParameter_FieldRotation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SIMDMat44f(cPtr, false);
  }

  public void setIsFieldRotated(boolean value) {
    GDXJNI.ForceFieldCommonParameter_IsFieldRotated_set(swigCPtr, this, value);
  }

  public boolean getIsFieldRotated() {
    return GDXJNI.ForceFieldCommonParameter_IsFieldRotated_get(swigCPtr, this);
  }

  public void setDeltaFrame(float value) {
    GDXJNI.ForceFieldCommonParameter_DeltaFrame_set(swigCPtr, this, value);
  }

  public float getDeltaFrame() {
    return GDXJNI.ForceFieldCommonParameter_DeltaFrame_get(swigCPtr, this);
  }

  public ForceFieldCommonParameter() {
    this(GDXJNI.new_ForceFieldCommonParameter(), true);
  }

}
