/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class ForceFieldFalloffConeParameter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ForceFieldFalloffConeParameter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ForceFieldFalloffConeParameter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_ForceFieldFalloffConeParameter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAnglePower(float value) {
    GDXJNI.ForceFieldFalloffConeParameter_AnglePower_set(swigCPtr, this, value);
  }

  public float getAnglePower() {
    return GDXJNI.ForceFieldFalloffConeParameter_AnglePower_get(swigCPtr, this);
  }

  public void setMinAngle(float value) {
    GDXJNI.ForceFieldFalloffConeParameter_MinAngle_set(swigCPtr, this, value);
  }

  public float getMinAngle() {
    return GDXJNI.ForceFieldFalloffConeParameter_MinAngle_get(swigCPtr, this);
  }

  public void setMaxAngle(float value) {
    GDXJNI.ForceFieldFalloffConeParameter_MaxAngle_set(swigCPtr, this, value);
  }

  public float getMaxAngle() {
    return GDXJNI.ForceFieldFalloffConeParameter_MaxAngle_get(swigCPtr, this);
  }

  public ForceFieldFalloffConeParameter() {
    this(GDXJNI.new_ForceFieldFalloffConeParameter(), true);
  }

}
