/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class GDX {
  public static int getUserTextureSlotMax() {
    return GDXJNI.UserTextureSlotMax_get();
  }

  public static int getUserUniformSlotMax() {
    return GDXJNI.UserUniformSlotMax_get();
  }

  public static int getTextureSlotMax() {
    return GDXJNI.TextureSlotMax_get();
  }

  public static int getLocalFieldSlotMax() {
    return GDXJNI.LocalFieldSlotMax_get();
  }

  public static float getEFK_PI() {
    return GDXJNI.EFK_PI_get();
  }

}
