/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class InstanceEasingFloat {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected InstanceEasingFloat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InstanceEasingFloat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_InstanceEasingFloat(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStart(float value) {
    GDXJNI.InstanceEasingFloat_start_set(swigCPtr, this, value);
  }

  public float getStart() {
    return GDXJNI.InstanceEasingFloat_start_get(swigCPtr, this);
  }

  public void setMiddle(float value) {
    GDXJNI.InstanceEasingFloat_middle_set(swigCPtr, this, value);
  }

  public float getMiddle() {
    return GDXJNI.InstanceEasingFloat_middle_get(swigCPtr, this);
  }

  public void setEnd(float value) {
    GDXJNI.InstanceEasingFloat_end_set(swigCPtr, this, value);
  }

  public float getEnd() {
    return GDXJNI.InstanceEasingFloat_end_get(swigCPtr, this);
  }

  public void setRate(float value) {
    GDXJNI.InstanceEasingFloat_Rate_set(swigCPtr, this, value);
  }

  public float getRate() {
    return GDXJNI.InstanceEasingFloat_Rate_get(swigCPtr, this);
  }

  public InstanceEasingFloat() {
    this(GDXJNI.new_InstanceEasingFloat(), true);
  }

}
