/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class InternalStructEasingVector2D {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected InternalStructEasingVector2D(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InternalStructEasingVector2D obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_InternalStructEasingVector2D(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStart(InternalStructRandomVector2D value) {
    GDXJNI.InternalStructEasingVector2D_start_set(swigCPtr, this, InternalStructRandomVector2D.getCPtr(value), value);
  }

  public InternalStructRandomVector2D getStart() {
    long cPtr = GDXJNI.InternalStructEasingVector2D_start_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InternalStructRandomVector2D(cPtr, false);
  }

  public void setEnd(InternalStructRandomVector2D value) {
    GDXJNI.InternalStructEasingVector2D_end_set(swigCPtr, this, InternalStructRandomVector2D.getCPtr(value), value);
  }

  public InternalStructRandomVector2D getEnd() {
    long cPtr = GDXJNI.InternalStructEasingVector2D_end_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InternalStructRandomVector2D(cPtr, false);
  }

  public void setEasingA(float value) {
    GDXJNI.InternalStructEasingVector2D_easingA_set(swigCPtr, this, value);
  }

  public float getEasingA() {
    return GDXJNI.InternalStructEasingVector2D_easingA_get(swigCPtr, this);
  }

  public void setEasingB(float value) {
    GDXJNI.InternalStructEasingVector2D_easingB_set(swigCPtr, this, value);
  }

  public float getEasingB() {
    return GDXJNI.InternalStructEasingVector2D_easingB_get(swigCPtr, this);
  }

  public void setEasingC(float value) {
    GDXJNI.InternalStructEasingVector2D_easingC_set(swigCPtr, this, value);
  }

  public float getEasingC() {
    return GDXJNI.InternalStructEasingVector2D_easingC_get(swigCPtr, this);
  }

  public InternalStructEasingVector2D() {
    this(GDXJNI.new_InternalStructEasingVector2D(), true);
  }

}
