/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class InternalStructRandomVector2D {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected InternalStructRandomVector2D(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InternalStructRandomVector2D obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_InternalStructRandomVector2D(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMax(InternalStructVector2D value) {
    GDXJNI.InternalStructRandomVector2D_max_set(swigCPtr, this, InternalStructVector2D.getCPtr(value), value);
  }

  public InternalStructVector2D getMax() {
    long cPtr = GDXJNI.InternalStructRandomVector2D_max_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InternalStructVector2D(cPtr, false);
  }

  public void setMin(InternalStructVector2D value) {
    GDXJNI.InternalStructRandomVector2D_min_set(swigCPtr, this, InternalStructVector2D.getCPtr(value), value);
  }

  public InternalStructVector2D getMin() {
    long cPtr = GDXJNI.InternalStructRandomVector2D_min_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InternalStructVector2D(cPtr, false);
  }

  public InternalStructRandomVector2D() {
    this(GDXJNI.new_InternalStructRandomVector2D(), true);
  }

}
