/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class InternalStructEasingFloat {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected InternalStructEasingFloat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InternalStructEasingFloat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_InternalStructEasingFloat(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStart(InternalStructRandomFloat value) {
    GDXJNI.InternalStructEasingFloat_start_set(swigCPtr, this, InternalStructRandomFloat.getCPtr(value), value);
  }

  public InternalStructRandomFloat getStart() {
    long cPtr = GDXJNI.InternalStructEasingFloat_start_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InternalStructRandomFloat(cPtr, false);
  }

  public void setEnd(InternalStructRandomFloat value) {
    GDXJNI.InternalStructEasingFloat_end_set(swigCPtr, this, InternalStructRandomFloat.getCPtr(value), value);
  }

  public InternalStructRandomFloat getEnd() {
    long cPtr = GDXJNI.InternalStructEasingFloat_end_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InternalStructRandomFloat(cPtr, false);
  }

  public void setEasingA(float value) {
    GDXJNI.InternalStructEasingFloat_easingA_set(swigCPtr, this, value);
  }

  public float getEasingA() {
    return GDXJNI.InternalStructEasingFloat_easingA_get(swigCPtr, this);
  }

  public void setEasingB(float value) {
    GDXJNI.InternalStructEasingFloat_easingB_set(swigCPtr, this, value);
  }

  public float getEasingB() {
    return GDXJNI.InternalStructEasingFloat_easingB_get(swigCPtr, this);
  }

  public void setEasingC(float value) {
    GDXJNI.InternalStructEasingFloat_easingC_set(swigCPtr, this, value);
  }

  public float getEasingC() {
    return GDXJNI.InternalStructEasingFloat_easingC_get(swigCPtr, this);
  }

  public InternalStructEasingFloat() {
    this(GDXJNI.new_InternalStructEasingFloat(), true);
  }

}
