/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class InternalStructRandomInt {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected InternalStructRandomInt(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InternalStructRandomInt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_InternalStructRandomInt(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMax(int value) {
    GDXJNI.InternalStructRandomInt_max_set(swigCPtr, this, value);
  }

  public int getMax() {
    return GDXJNI.InternalStructRandomInt_max_get(swigCPtr, this);
  }

  public void setMin(int value) {
    GDXJNI.InternalStructRandomInt_min_set(swigCPtr, this, value);
  }

  public int getMin() {
    return GDXJNI.InternalStructRandomInt_min_get(swigCPtr, this);
  }

  public InternalStructRandomInt() {
    this(GDXJNI.new_InternalStructRandomInt(), true);
  }

}
