/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class InternalStructEasingVector3D {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected InternalStructEasingVector3D(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InternalStructEasingVector3D obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_InternalStructEasingVector3D(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStart(InternalStructRandomVector3D value) {
    GDXJNI.InternalStructEasingVector3D_start_set(swigCPtr, this, InternalStructRandomVector3D.getCPtr(value), value);
  }

  public InternalStructRandomVector3D getStart() {
    long cPtr = GDXJNI.InternalStructEasingVector3D_start_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InternalStructRandomVector3D(cPtr, false);
  }

  public void setEnd(InternalStructRandomVector3D value) {
    GDXJNI.InternalStructEasingVector3D_end_set(swigCPtr, this, InternalStructRandomVector3D.getCPtr(value), value);
  }

  public InternalStructRandomVector3D getEnd() {
    long cPtr = GDXJNI.InternalStructEasingVector3D_end_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InternalStructRandomVector3D(cPtr, false);
  }

  public void setEasingA(float value) {
    GDXJNI.InternalStructEasingVector3D_easingA_set(swigCPtr, this, value);
  }

  public float getEasingA() {
    return GDXJNI.InternalStructEasingVector3D_easingA_get(swigCPtr, this);
  }

  public void setEasingB(float value) {
    GDXJNI.InternalStructEasingVector3D_easingB_set(swigCPtr, this, value);
  }

  public float getEasingB() {
    return GDXJNI.InternalStructEasingVector3D_easingB_get(swigCPtr, this);
  }

  public void setEasingC(float value) {
    GDXJNI.InternalStructEasingVector3D_easingC_set(swigCPtr, this, value);
  }

  public float getEasingC() {
    return GDXJNI.InternalStructEasingVector3D_easingC_get(swigCPtr, this);
  }

  public InternalStructEasingVector3D() {
    this(GDXJNI.new_InternalStructEasingVector3D(), true);
  }

}
