/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class InternalStructRandomFloat {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected InternalStructRandomFloat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InternalStructRandomFloat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_InternalStructRandomFloat(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMax(float value) {
    GDXJNI.InternalStructRandomFloat_max_set(swigCPtr, this, value);
  }

  public float getMax() {
    return GDXJNI.InternalStructRandomFloat_max_get(swigCPtr, this);
  }

  public void setMin(float value) {
    GDXJNI.InternalStructRandomFloat_min_set(swigCPtr, this, value);
  }

  public float getMin() {
    return GDXJNI.InternalStructRandomFloat_min_get(swigCPtr, this);
  }

  public InternalStructRandomFloat() {
    this(GDXJNI.new_InternalStructRandomFloat(), true);
  }

}
