/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public final class LocalForceFieldType {
  public final static LocalForceFieldType None = new LocalForceFieldType("None", GDXJNI.LocalForceFieldType_None_get());
  public final static LocalForceFieldType Force = new LocalForceFieldType("Force", GDXJNI.LocalForceFieldType_Force_get());
  public final static LocalForceFieldType Wind = new LocalForceFieldType("Wind", GDXJNI.LocalForceFieldType_Wind_get());
  public final static LocalForceFieldType Vortex = new LocalForceFieldType("Vortex", GDXJNI.LocalForceFieldType_Vortex_get());
  public final static LocalForceFieldType Turbulence = new LocalForceFieldType("Turbulence", GDXJNI.LocalForceFieldType_Turbulence_get());
  public final static LocalForceFieldType Drag = new LocalForceFieldType("Drag", GDXJNI.LocalForceFieldType_Drag_get());
  public final static LocalForceFieldType Gravity = new LocalForceFieldType("Gravity", GDXJNI.LocalForceFieldType_Gravity_get());
  public final static LocalForceFieldType AttractiveForce = new LocalForceFieldType("AttractiveForce", GDXJNI.LocalForceFieldType_AttractiveForce_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static LocalForceFieldType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + LocalForceFieldType.class + " with value " + swigValue);
  }

  private LocalForceFieldType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private LocalForceFieldType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private LocalForceFieldType(String swigName, LocalForceFieldType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static LocalForceFieldType[] swigValues = { None, Force, Wind, Vortex, Turbulence, Drag, Gravity, AttractiveForce };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

