/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public final class LocationAbsType {
  public final static LocationAbsType None = new LocationAbsType("None", GDXJNI.LocationAbsType_None_get());
  public final static LocationAbsType Gravity = new LocationAbsType("Gravity", GDXJNI.LocationAbsType_Gravity_get());
  public final static LocationAbsType AttractiveForce = new LocationAbsType("AttractiveForce", GDXJNI.LocationAbsType_AttractiveForce_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static LocationAbsType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + LocationAbsType.class + " with value " + swigValue);
  }

  private LocationAbsType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private LocationAbsType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private LocationAbsType(String swigName, LocationAbsType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static LocationAbsType[] swigValues = { None, Gravity, AttractiveForce };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

