/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class LocalForceFieldParameter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LocalForceFieldParameter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LocalForceFieldParameter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_LocalForceFieldParameter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHasValue(boolean value) {
    GDXJNI.LocalForceFieldParameter_HasValue_set(swigCPtr, this, value);
  }

  public boolean getHasValue() {
    return GDXJNI.LocalForceFieldParameter_HasValue_get(swigCPtr, this);
  }

  public void setIsGlobalEnabled(boolean value) {
    GDXJNI.LocalForceFieldParameter_IsGlobalEnabled_set(swigCPtr, this, value);
  }

  public boolean getIsGlobalEnabled() {
    return GDXJNI.LocalForceFieldParameter_IsGlobalEnabled_get(swigCPtr, this);
  }

  public LocalForceFieldParameter() {
    this(GDXJNI.new_LocalForceFieldParameter(), true);
  }

}
