/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public final class LocalForceFieldFalloffType {
  public final static LocalForceFieldFalloffType None = new LocalForceFieldFalloffType("None", GDXJNI.LocalForceFieldFalloffType_None_get());
  public final static LocalForceFieldFalloffType Sphere = new LocalForceFieldFalloffType("Sphere", GDXJNI.LocalForceFieldFalloffType_Sphere_get());
  public final static LocalForceFieldFalloffType Tube = new LocalForceFieldFalloffType("Tube", GDXJNI.LocalForceFieldFalloffType_Tube_get());
  public final static LocalForceFieldFalloffType Cone = new LocalForceFieldFalloffType("Cone", GDXJNI.LocalForceFieldFalloffType_Cone_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static LocalForceFieldFalloffType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + LocalForceFieldFalloffType.class + " with value " + swigValue);
  }

  private LocalForceFieldFalloffType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private LocalForceFieldFalloffType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private LocalForceFieldFalloffType(String swigName, LocalForceFieldFalloffType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static LocalForceFieldFalloffType[] swigValues = { None, Sphere, Tube, Cone };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

