/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class LocalForceFieldInstance {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LocalForceFieldInstance(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LocalForceFieldInstance obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_LocalForceFieldInstance(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVelocities(ArrayLocalForceFieldVelocities value) {
    GDXJNI.LocalForceFieldInstance_Velocities_set(swigCPtr, this, ArrayLocalForceFieldVelocities.getCPtr(value), value);
  }

  public ArrayLocalForceFieldVelocities getVelocities() {
    long cPtr = GDXJNI.LocalForceFieldInstance_Velocities_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ArrayLocalForceFieldVelocities(cPtr, false);
  }

  public void setExternalVelocity(SIMDVec3f value) {
    GDXJNI.LocalForceFieldInstance_ExternalVelocity_set(swigCPtr, this, SIMDVec3f.getCPtr(value), value);
  }

  public SIMDVec3f getExternalVelocity() {
    long cPtr = GDXJNI.LocalForceFieldInstance_ExternalVelocity_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SIMDVec3f(cPtr, false);
  }

  public void setVelocitySum(SIMDVec3f value) {
    GDXJNI.LocalForceFieldInstance_VelocitySum_set(swigCPtr, this, SIMDVec3f.getCPtr(value), value);
  }

  public SIMDVec3f getVelocitySum() {
    long cPtr = GDXJNI.LocalForceFieldInstance_VelocitySum_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SIMDVec3f(cPtr, false);
  }

  public void setModifyLocation(SIMDVec3f value) {
    GDXJNI.LocalForceFieldInstance_ModifyLocation_set(swigCPtr, this, SIMDVec3f.getCPtr(value), value);
  }

  public SIMDVec3f getModifyLocation() {
    long cPtr = GDXJNI.LocalForceFieldInstance_ModifyLocation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SIMDVec3f(cPtr, false);
  }

  public void setGlobalVelocitySum(SIMDVec3f value) {
    GDXJNI.LocalForceFieldInstance_GlobalVelocitySum_set(swigCPtr, this, SIMDVec3f.getCPtr(value), value);
  }

  public SIMDVec3f getGlobalVelocitySum() {
    long cPtr = GDXJNI.LocalForceFieldInstance_GlobalVelocitySum_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SIMDVec3f(cPtr, false);
  }

  public void setGlobalModifyLocation(SIMDVec3f value) {
    GDXJNI.LocalForceFieldInstance_GlobalModifyLocation_set(swigCPtr, this, SIMDVec3f.getCPtr(value), value);
  }

  public SIMDVec3f getGlobalModifyLocation() {
    long cPtr = GDXJNI.LocalForceFieldInstance_GlobalModifyLocation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SIMDVec3f(cPtr, false);
  }

  public LocalForceFieldInstance() {
    this(GDXJNI.new_LocalForceFieldInstance(), true);
  }

}
