/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class MaterialTextureParameter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MaterialTextureParameter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MaterialTextureParameter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_MaterialTextureParameter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(int value) {
    GDXJNI.MaterialTextureParameter_Type_set(swigCPtr, this, value);
  }

  public int getType() {
    return GDXJNI.MaterialTextureParameter_Type_get(swigCPtr, this);
  }

  public void setIndex(int value) {
    GDXJNI.MaterialTextureParameter_Index_set(swigCPtr, this, value);
  }

  public int getIndex() {
    return GDXJNI.MaterialTextureParameter_Index_get(swigCPtr, this);
  }

  public MaterialTextureParameter() {
    this(GDXJNI.new_MaterialTextureParameter(), true);
  }

}
