/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class Matrix44 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Matrix44(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Matrix44 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_Matrix44(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Matrix44() {
    this(GDXJNI.new_Matrix44(), true);
  }

  public void setValues(SWIGTYPE_p_a_4__float value) {
    GDXJNI.Matrix44_Values_set(swigCPtr, this, SWIGTYPE_p_a_4__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_4__float getValues() {
    long cPtr = GDXJNI.Matrix44_Values_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_4__float(cPtr, false);
  }

}
