/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class NodeRendererTextureUVTypeParameter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NodeRendererTextureUVTypeParameter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NodeRendererTextureUVTypeParameter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_NodeRendererTextureUVTypeParameter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(TextureUVType value) {
    GDXJNI.NodeRendererTextureUVTypeParameter_Type_set(swigCPtr, this, value.swigValue());
  }

  public TextureUVType getType() {
    return TextureUVType.swigToEnum(GDXJNI.NodeRendererTextureUVTypeParameter_Type_get(swigCPtr, this));
  }

  public void setTileLength(float value) {
    GDXJNI.NodeRendererTextureUVTypeParameter_TileLength_set(swigCPtr, this, value);
  }

  public float getTileLength() {
    return GDXJNI.NodeRendererTextureUVTypeParameter_TileLength_get(swigCPtr, this);
  }

  public void setTileEdgeHead(int value) {
    GDXJNI.NodeRendererTextureUVTypeParameter_TileEdgeHead_set(swigCPtr, this, value);
  }

  public int getTileEdgeHead() {
    return GDXJNI.NodeRendererTextureUVTypeParameter_TileEdgeHead_get(swigCPtr, this);
  }

  public void setTileEdgeTail(int value) {
    GDXJNI.NodeRendererTextureUVTypeParameter_TileEdgeTail_set(swigCPtr, this, value);
  }

  public int getTileEdgeTail() {
    return GDXJNI.NodeRendererTextureUVTypeParameter_TileEdgeTail_get(swigCPtr, this);
  }

  public void setTileLoopAreaBegin(float value) {
    GDXJNI.NodeRendererTextureUVTypeParameter_TileLoopAreaBegin_set(swigCPtr, this, value);
  }

  public float getTileLoopAreaBegin() {
    return GDXJNI.NodeRendererTextureUVTypeParameter_TileLoopAreaBegin_get(swigCPtr, this);
  }

  public void setTileLoopAreaEnd(float value) {
    GDXJNI.NodeRendererTextureUVTypeParameter_TileLoopAreaEnd_set(swigCPtr, this, value);
  }

  public float getTileLoopAreaEnd() {
    return GDXJNI.NodeRendererTextureUVTypeParameter_TileLoopAreaEnd_get(swigCPtr, this);
  }

  public NodeRendererTextureUVTypeParameter() {
    this(GDXJNI.new_NodeRendererTextureUVTypeParameter(), true);
  }

}
