/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class ParameterScalingSinglePVA {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ParameterScalingSinglePVA(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParameterScalingSinglePVA obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_ParameterScalingSinglePVA(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPosition(InternalStructRandomFloat value) {
    GDXJNI.ParameterScalingSinglePVA_Position_set(swigCPtr, this, InternalStructRandomFloat.getCPtr(value), value);
  }

  public InternalStructRandomFloat getPosition() {
    long cPtr = GDXJNI.ParameterScalingSinglePVA_Position_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InternalStructRandomFloat(cPtr, false);
  }

  public void setVelocity(InternalStructRandomFloat value) {
    GDXJNI.ParameterScalingSinglePVA_Velocity_set(swigCPtr, this, InternalStructRandomFloat.getCPtr(value), value);
  }

  public InternalStructRandomFloat getVelocity() {
    long cPtr = GDXJNI.ParameterScalingSinglePVA_Velocity_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InternalStructRandomFloat(cPtr, false);
  }

  public void setAcceleration(InternalStructRandomFloat value) {
    GDXJNI.ParameterScalingSinglePVA_Acceleration_set(swigCPtr, this, InternalStructRandomFloat.getCPtr(value), value);
  }

  public InternalStructRandomFloat getAcceleration() {
    long cPtr = GDXJNI.ParameterScalingSinglePVA_Acceleration_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InternalStructRandomFloat(cPtr, false);
  }

  public ParameterScalingSinglePVA() {
    this(GDXJNI.new_ParameterScalingSinglePVA(), true);
  }

}
