/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class ParameterTranslationNurbsCurve {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ParameterTranslationNurbsCurve(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParameterTranslationNurbsCurve obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_ParameterTranslationNurbsCurve(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIndex(int value) {
    GDXJNI.ParameterTranslationNurbsCurve_Index_set(swigCPtr, this, value);
  }

  public int getIndex() {
    return GDXJNI.ParameterTranslationNurbsCurve_Index_get(swigCPtr, this);
  }

  public void setScale(float value) {
    GDXJNI.ParameterTranslationNurbsCurve_Scale_set(swigCPtr, this, value);
  }

  public float getScale() {
    return GDXJNI.ParameterTranslationNurbsCurve_Scale_get(swigCPtr, this);
  }

  public void setMoveSpeed(float value) {
    GDXJNI.ParameterTranslationNurbsCurve_MoveSpeed_set(swigCPtr, this, value);
  }

  public float getMoveSpeed() {
    return GDXJNI.ParameterTranslationNurbsCurve_MoveSpeed_get(swigCPtr, this);
  }

  public void setLoopType(int value) {
    GDXJNI.ParameterTranslationNurbsCurve_LoopType_set(swigCPtr, this, value);
  }

  public int getLoopType() {
    return GDXJNI.ParameterTranslationNurbsCurve_LoopType_get(swigCPtr, this);
  }

  public ParameterTranslationNurbsCurve() {
    this(GDXJNI.new_ParameterTranslationNurbsCurve(), true);
  }

}
