/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class ParameterCommonValues_8 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ParameterCommonValues_8(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParameterCommonValues_8 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_ParameterCommonValues_8(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMaxGeneration(int value) {
    GDXJNI.ParameterCommonValues_8_MaxGeneration_set(swigCPtr, this, value);
  }

  public int getMaxGeneration() {
    return GDXJNI.ParameterCommonValues_8_MaxGeneration_get(swigCPtr, this);
  }

  public void setTranslationBindType(BindType value) {
    GDXJNI.ParameterCommonValues_8_TranslationBindType_set(swigCPtr, this, value.swigValue());
  }

  public BindType getTranslationBindType() {
    return BindType.swigToEnum(GDXJNI.ParameterCommonValues_8_TranslationBindType_get(swigCPtr, this));
  }

  public void setRotationBindType(BindType value) {
    GDXJNI.ParameterCommonValues_8_RotationBindType_set(swigCPtr, this, value.swigValue());
  }

  public BindType getRotationBindType() {
    return BindType.swigToEnum(GDXJNI.ParameterCommonValues_8_RotationBindType_get(swigCPtr, this));
  }

  public void setScalingBindType(BindType value) {
    GDXJNI.ParameterCommonValues_8_ScalingBindType_set(swigCPtr, this, value.swigValue());
  }

  public BindType getScalingBindType() {
    return BindType.swigToEnum(GDXJNI.ParameterCommonValues_8_ScalingBindType_get(swigCPtr, this));
  }

  public void setRemoveWhenLifeIsExtinct(int value) {
    GDXJNI.ParameterCommonValues_8_RemoveWhenLifeIsExtinct_set(swigCPtr, this, value);
  }

  public int getRemoveWhenLifeIsExtinct() {
    return GDXJNI.ParameterCommonValues_8_RemoveWhenLifeIsExtinct_get(swigCPtr, this);
  }

  public void setRemoveWhenParentIsRemoved(int value) {
    GDXJNI.ParameterCommonValues_8_RemoveWhenParentIsRemoved_set(swigCPtr, this, value);
  }

  public int getRemoveWhenParentIsRemoved() {
    return GDXJNI.ParameterCommonValues_8_RemoveWhenParentIsRemoved_get(swigCPtr, this);
  }

  public void setRemoveWhenChildrenIsExtinct(int value) {
    GDXJNI.ParameterCommonValues_8_RemoveWhenChildrenIsExtinct_set(swigCPtr, this, value);
  }

  public int getRemoveWhenChildrenIsExtinct() {
    return GDXJNI.ParameterCommonValues_8_RemoveWhenChildrenIsExtinct_get(swigCPtr, this);
  }

  public void setLife(InternalStructRandomInt value) {
    GDXJNI.ParameterCommonValues_8_life_set(swigCPtr, this, InternalStructRandomInt.getCPtr(value), value);
  }

  public InternalStructRandomInt getLife() {
    long cPtr = GDXJNI.ParameterCommonValues_8_life_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InternalStructRandomInt(cPtr, false);
  }

  public void setGenerationTime(float value) {
    GDXJNI.ParameterCommonValues_8_GenerationTime_set(swigCPtr, this, value);
  }

  public float getGenerationTime() {
    return GDXJNI.ParameterCommonValues_8_GenerationTime_get(swigCPtr, this);
  }

  public void setGenerationTimeOffset(float value) {
    GDXJNI.ParameterCommonValues_8_GenerationTimeOffset_set(swigCPtr, this, value);
  }

  public float getGenerationTimeOffset() {
    return GDXJNI.ParameterCommonValues_8_GenerationTimeOffset_get(swigCPtr, this);
  }

  public ParameterCommonValues_8() {
    this(GDXJNI.new_ParameterCommonValues_8(), true);
  }

}
