/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class ParameterTranslationFixed {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ParameterTranslationFixed(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParameterTranslationFixed obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_ParameterTranslationFixed(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRefEq(int value) {
    GDXJNI.ParameterTranslationFixed_RefEq_set(swigCPtr, this, value);
  }

  public int getRefEq() {
    return GDXJNI.ParameterTranslationFixed_RefEq_get(swigCPtr, this);
  }

  public void setPosition(Vector3D value) {
    GDXJNI.ParameterTranslationFixed_Position_set(swigCPtr, this, Vector3D.getCPtr(value), value);
  }

  public Vector3D getPosition() {
    long cPtr = GDXJNI.ParameterTranslationFixed_Position_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Vector3D(cPtr, false);
  }

  public ParameterTranslationFixed() {
    this(GDXJNI.new_ParameterTranslationFixed(), true);
  }

}
