/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class ParameterTranslationViewOffset {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ParameterTranslationViewOffset(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParameterTranslationViewOffset obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_ParameterTranslationViewOffset(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDistance(InternalStructRandomFloat value) {
    GDXJNI.ParameterTranslationViewOffset_distance_set(swigCPtr, this, InternalStructRandomFloat.getCPtr(value), value);
  }

  public InternalStructRandomFloat getDistance() {
    long cPtr = GDXJNI.ParameterTranslationViewOffset_distance_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InternalStructRandomFloat(cPtr, false);
  }

  public ParameterTranslationViewOffset() {
    this(GDXJNI.new_ParameterTranslationViewOffset(), true);
  }

}
