/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public final class ParameterCustomDataType {
  public final static ParameterCustomDataType None = new ParameterCustomDataType("None", GDXJNI.None_get());
  public final static ParameterCustomDataType Fixed2D = new ParameterCustomDataType("Fixed2D", GDXJNI.Fixed2D_get());
  public final static ParameterCustomDataType Random2D = new ParameterCustomDataType("Random2D", GDXJNI.Random2D_get());
  public final static ParameterCustomDataType Easing2D = new ParameterCustomDataType("Easing2D", GDXJNI.Easing2D_get());
  public final static ParameterCustomDataType FCurve2D = new ParameterCustomDataType("FCurve2D", GDXJNI.FCurve2D_get());
  public final static ParameterCustomDataType Fixed4D = new ParameterCustomDataType("Fixed4D", GDXJNI.Fixed4D_get());
  public final static ParameterCustomDataType FCurveColor = new ParameterCustomDataType("FCurveColor", GDXJNI.FCurveColor_get());
  public final static ParameterCustomDataType DynamicInput = new ParameterCustomDataType("DynamicInput", GDXJNI.DynamicInput_get());
  public final static ParameterCustomDataType Unknown = new ParameterCustomDataType("Unknown");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ParameterCustomDataType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ParameterCustomDataType.class + " with value " + swigValue);
  }

  private ParameterCustomDataType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ParameterCustomDataType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ParameterCustomDataType(String swigName, ParameterCustomDataType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ParameterCustomDataType[] swigValues = { None, Fixed2D, Random2D, Easing2D, FCurve2D, Fixed4D, FCurveColor, DynamicInput, Unknown };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

