/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public final class ParameterSoundType {
  public final static ParameterSoundType ParameterSoundType_None = new ParameterSoundType("ParameterSoundType_None", GDXJNI.ParameterSoundType_None_get());
  public final static ParameterSoundType ParameterSoundType_Use = new ParameterSoundType("ParameterSoundType_Use", GDXJNI.ParameterSoundType_Use_get());
  public final static ParameterSoundType ParameterSoundType_DWORD = new ParameterSoundType("ParameterSoundType_DWORD", GDXJNI.ParameterSoundType_DWORD_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ParameterSoundType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ParameterSoundType.class + " with value " + swigValue);
  }

  private ParameterSoundType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ParameterSoundType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ParameterSoundType(String swigName, ParameterSoundType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ParameterSoundType[] swigValues = { ParameterSoundType_None, ParameterSoundType_Use, ParameterSoundType_DWORD };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

