/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class ParameterScalingEasing {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ParameterScalingEasing(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParameterScalingEasing obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_ParameterScalingEasing(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRefEqS(RefMinMax value) {
    GDXJNI.ParameterScalingEasing_RefEqS_set(swigCPtr, this, RefMinMax.getCPtr(value), value);
  }

  public RefMinMax getRefEqS() {
    long cPtr = GDXJNI.ParameterScalingEasing_RefEqS_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RefMinMax(cPtr, false);
  }

  public void setRefEqE(RefMinMax value) {
    GDXJNI.ParameterScalingEasing_RefEqE_set(swigCPtr, this, RefMinMax.getCPtr(value), value);
  }

  public RefMinMax getRefEqE() {
    long cPtr = GDXJNI.ParameterScalingEasing_RefEqE_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RefMinMax(cPtr, false);
  }

  public void setPosition(InternalStructEasingVector3D value) {
    GDXJNI.ParameterScalingEasing_Position_set(swigCPtr, this, InternalStructEasingVector3D.getCPtr(value), value);
  }

  public InternalStructEasingVector3D getPosition() {
    long cPtr = GDXJNI.ParameterScalingEasing_Position_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InternalStructEasingVector3D(cPtr, false);
  }

  public ParameterScalingEasing() {
    this(GDXJNI.new_ParameterScalingEasing(), true);
  }

}
