/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class ParameterRotationAxisPVA {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ParameterRotationAxisPVA(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParameterRotationAxisPVA obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_ParameterRotationAxisPVA(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAxis(InternalStructRandomVector3D value) {
    GDXJNI.ParameterRotationAxisPVA_axis_set(swigCPtr, this, InternalStructRandomVector3D.getCPtr(value), value);
  }

  public InternalStructRandomVector3D getAxis() {
    long cPtr = GDXJNI.ParameterRotationAxisPVA_axis_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InternalStructRandomVector3D(cPtr, false);
  }

  public void setRotation(InternalStructRandomFloat value) {
    GDXJNI.ParameterRotationAxisPVA_rotation_set(swigCPtr, this, InternalStructRandomFloat.getCPtr(value), value);
  }

  public InternalStructRandomFloat getRotation() {
    long cPtr = GDXJNI.ParameterRotationAxisPVA_rotation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InternalStructRandomFloat(cPtr, false);
  }

  public void setVelocity(InternalStructRandomFloat value) {
    GDXJNI.ParameterRotationAxisPVA_velocity_set(swigCPtr, this, InternalStructRandomFloat.getCPtr(value), value);
  }

  public InternalStructRandomFloat getVelocity() {
    long cPtr = GDXJNI.ParameterRotationAxisPVA_velocity_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InternalStructRandomFloat(cPtr, false);
  }

  public void setAcceleration(InternalStructRandomFloat value) {
    GDXJNI.ParameterRotationAxisPVA_acceleration_set(swigCPtr, this, InternalStructRandomFloat.getCPtr(value), value);
  }

  public InternalStructRandomFloat getAcceleration() {
    long cPtr = GDXJNI.ParameterRotationAxisPVA_acceleration_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InternalStructRandomFloat(cPtr, false);
  }

  public ParameterRotationAxisPVA() {
    this(GDXJNI.new_ParameterRotationAxisPVA(), true);
  }

}
