/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class ParameterScalingPVA {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ParameterScalingPVA(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParameterScalingPVA obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_ParameterScalingPVA(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRefEqP(RefMinMax value) {
    GDXJNI.ParameterScalingPVA_RefEqP_set(swigCPtr, this, RefMinMax.getCPtr(value), value);
  }

  public RefMinMax getRefEqP() {
    long cPtr = GDXJNI.ParameterScalingPVA_RefEqP_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RefMinMax(cPtr, false);
  }

  public void setRefEqV(RefMinMax value) {
    GDXJNI.ParameterScalingPVA_RefEqV_set(swigCPtr, this, RefMinMax.getCPtr(value), value);
  }

  public RefMinMax getRefEqV() {
    long cPtr = GDXJNI.ParameterScalingPVA_RefEqV_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RefMinMax(cPtr, false);
  }

  public void setRefEqA(RefMinMax value) {
    GDXJNI.ParameterScalingPVA_RefEqA_set(swigCPtr, this, RefMinMax.getCPtr(value), value);
  }

  public RefMinMax getRefEqA() {
    long cPtr = GDXJNI.ParameterScalingPVA_RefEqA_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RefMinMax(cPtr, false);
  }

  public void setPosition(InternalStructRandomVector3D value) {
    GDXJNI.ParameterScalingPVA_Position_set(swigCPtr, this, InternalStructRandomVector3D.getCPtr(value), value);
  }

  public InternalStructRandomVector3D getPosition() {
    long cPtr = GDXJNI.ParameterScalingPVA_Position_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InternalStructRandomVector3D(cPtr, false);
  }

  public void setVelocity(InternalStructRandomVector3D value) {
    GDXJNI.ParameterScalingPVA_Velocity_set(swigCPtr, this, InternalStructRandomVector3D.getCPtr(value), value);
  }

  public InternalStructRandomVector3D getVelocity() {
    long cPtr = GDXJNI.ParameterScalingPVA_Velocity_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InternalStructRandomVector3D(cPtr, false);
  }

  public void setAcceleration(InternalStructRandomVector3D value) {
    GDXJNI.ParameterScalingPVA_Acceleration_set(swigCPtr, this, InternalStructRandomVector3D.getCPtr(value), value);
  }

  public InternalStructRandomVector3D getAcceleration() {
    long cPtr = GDXJNI.ParameterScalingPVA_Acceleration_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InternalStructRandomVector3D(cPtr, false);
  }

  public ParameterScalingPVA() {
    this(GDXJNI.new_ParameterScalingPVA(), true);
  }

}
