/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class ParameterCustomDataFCurveColor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ParameterCustomDataFCurveColor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParameterCustomDataFCurveColor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_ParameterCustomDataFCurveColor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setValues(FCurveVectorColor value) {
    GDXJNI.ParameterCustomDataFCurveColor_Values_set(swigCPtr, this, FCurveVectorColor.getCPtr(value), value);
  }

  public FCurveVectorColor getValues() {
    long cPtr = GDXJNI.ParameterCustomDataFCurveColor_Values_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FCurveVectorColor(cPtr, false);
  }

  public ParameterCustomDataFCurveColor() {
    this(GDXJNI.new_ParameterCustomDataFCurveColor(), true);
  }

}
