/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class ParameterCustomDataEasing {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ParameterCustomDataEasing(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParameterCustomDataEasing obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_ParameterCustomDataEasing(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setValues(InternalStructEasingVector2D value) {
    GDXJNI.ParameterCustomDataEasing_Values_set(swigCPtr, this, InternalStructEasingVector2D.getCPtr(value), value);
  }

  public InternalStructEasingVector2D getValues() {
    long cPtr = GDXJNI.ParameterCustomDataEasing_Values_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InternalStructEasingVector2D(cPtr, false);
  }

  public ParameterCustomDataEasing() {
    this(GDXJNI.new_ParameterCustomDataEasing(), true);
  }

}
