/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class RefMinMax {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RefMinMax(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RefMinMax obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_RefMinMax(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMax(int value) {
    GDXJNI.RefMinMax_Max_set(swigCPtr, this, value);
  }

  public int getMax() {
    return GDXJNI.RefMinMax_Max_get(swigCPtr, this);
  }

  public void setMin(int value) {
    GDXJNI.RefMinMax_Min_set(swigCPtr, this, value);
  }

  public int getMin() {
    return GDXJNI.RefMinMax_Min_get(swigCPtr, this);
  }

  public RefMinMax() {
    this(GDXJNI.new_RefMinMax(), true);
  }

}
