/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public final class ReloadingThreadType {
  public final static ReloadingThreadType Main = new ReloadingThreadType("Main");
  public final static ReloadingThreadType Render = new ReloadingThreadType("Render");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ReloadingThreadType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ReloadingThreadType.class + " with value " + swigValue);
  }

  private ReloadingThreadType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ReloadingThreadType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ReloadingThreadType(String swigName, ReloadingThreadType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ReloadingThreadType[] swigValues = { Main, Render };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

