/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public final class RendererMaterialType {
  public final static RendererMaterialType Default = new RendererMaterialType("Default", GDXJNI.RendererMaterialType_Default_get());
  public final static RendererMaterialType BackDistortion = new RendererMaterialType("BackDistortion", GDXJNI.RendererMaterialType_BackDistortion_get());
  public final static RendererMaterialType Lighting = new RendererMaterialType("Lighting", GDXJNI.RendererMaterialType_Lighting_get());
  public final static RendererMaterialType File = new RendererMaterialType("File", GDXJNI.RendererMaterialType_File_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static RendererMaterialType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + RendererMaterialType.class + " with value " + swigValue);
  }

  private RendererMaterialType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private RendererMaterialType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private RendererMaterialType(String swigName, RendererMaterialType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static RendererMaterialType[] swigValues = { Default, BackDistortion, Lighting, File };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

