/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class RibbonPositionParameterCore {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RibbonPositionParameterCore(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RibbonPositionParameterCore obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_RibbonPositionParameterCore(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(int value) {
    GDXJNI.RibbonPositionParameterCore_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return GDXJNI.RibbonPositionParameterCore_type_get(swigCPtr, this);
  }

  public float getFixedLeftCoord() {
    return GDXJNI.RibbonPositionParameterCore_getFixedLeftCoord(swigCPtr, this);
  }

  public void setFixedLeftCoord(float value) {
    GDXJNI.RibbonPositionParameterCore_setFixedLeftCoord(swigCPtr, this, value);
  }

  public float getFixedRightCoord() {
    return GDXJNI.RibbonPositionParameterCore_getFixedRightCoord(swigCPtr, this);
  }

  public void setFixedRightCoord(float value) {
    GDXJNI.RibbonPositionParameterCore_setFixedRightCoord(swigCPtr, this, value);
  }

  public RibbonPositionParameterCore() {
    this(GDXJNI.new_RibbonPositionParameterCore(), true);
  }

  public final static int Default = GDXJNI.RibbonPositionParameterCore_Default_get();
  public final static int Fixed = GDXJNI.RibbonPositionParameterCore_Fixed_get();
  public final static int Parameter_DWORD = GDXJNI.RibbonPositionParameterCore_Parameter_DWORD_get();

}
