/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class RibbonColorParameterCore {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RibbonColorParameterCore(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RibbonColorParameterCore obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_RibbonColorParameterCore(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(int value) {
    GDXJNI.RibbonColorParameterCore_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return GDXJNI.RibbonColorParameterCore_type_get(swigCPtr, this);
  }

  public Color getFixedLeftColor() {
    return new Color(GDXJNI.RibbonColorParameterCore_getFixedLeftColor(swigCPtr, this), true);
  }

  public void setFixedLeftColor(Color value) {
    GDXJNI.RibbonColorParameterCore_setFixedLeftColor(swigCPtr, this, Color.getCPtr(value), value);
  }

  public Color getFixedRightColor() {
    return new Color(GDXJNI.RibbonColorParameterCore_getFixedRightColor(swigCPtr, this), true);
  }

  public void setFixedRightColor(Color value) {
    GDXJNI.RibbonColorParameterCore_setFixedRightColor(swigCPtr, this, Color.getCPtr(value), value);
  }

  public RibbonColorParameterCore() {
    this(GDXJNI.new_RibbonColorParameterCore(), true);
  }

  public final static int Default = GDXJNI.RibbonColorParameterCore_Default_get();
  public final static int Fixed = GDXJNI.RibbonColorParameterCore_Fixed_get();
  public final static int Parameter_DWORD = GDXJNI.RibbonColorParameterCore_Parameter_DWORD_get();

}
