/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class RingSingleValuesCore {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RingSingleValuesCore(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RingSingleValuesCore obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_RingSingleValuesCore(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCurrent(float value) {
    GDXJNI.RingSingleValuesCore_current_set(swigCPtr, this, value);
  }

  public float getCurrent() {
    return GDXJNI.RingSingleValuesCore_current_get(swigCPtr, this);
  }

  public void setEasing(InstanceEasingFloat value) {
    GDXJNI.RingSingleValuesCore_easing_set(swigCPtr, this, InstanceEasingFloat.getCPtr(value), value);
  }

  public InstanceEasingFloat getEasing() {
    long cPtr = GDXJNI.RingSingleValuesCore_easing_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InstanceEasingFloat(cPtr, false);
  }

  public RingSingleValuesCore() {
    this(GDXJNI.new_RingSingleValuesCore(), true);
  }

}
