/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class RingLocationValuesCore {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RingLocationValuesCore(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RingLocationValuesCore obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_RingLocationValuesCore(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCurrent(SIMDVec2f value) {
    GDXJNI.RingLocationValuesCore_current_set(swigCPtr, this, SIMDVec2f.getCPtr(value), value);
  }

  public SIMDVec2f getCurrent() {
    long cPtr = GDXJNI.RingLocationValuesCore_current_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SIMDVec2f(cPtr, false);
  }

  public RingLocationValuesCore() {
    this(GDXJNI.new_RingLocationValuesCore(), true);
  }

}
