/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class RingSingleParameterCore {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RingSingleParameterCore(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RingSingleParameterCore obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_RingSingleParameterCore(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(int value) {
    GDXJNI.RingSingleParameterCore_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return GDXJNI.RingSingleParameterCore_type_get(swigCPtr, this);
  }

  public void setFixed(float value) {
    GDXJNI.RingSingleParameterCore_fixed_set(swigCPtr, this, value);
  }

  public float getFixed() {
    return GDXJNI.RingSingleParameterCore_fixed_get(swigCPtr, this);
  }

  public void setRandom(InternalStructRandomFloat value) {
    GDXJNI.RingSingleParameterCore_random_set(swigCPtr, this, InternalStructRandomFloat.getCPtr(value), value);
  }

  public InternalStructRandomFloat getRandom() {
    long cPtr = GDXJNI.RingSingleParameterCore_random_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InternalStructRandomFloat(cPtr, false);
  }

  public void setEasing(ParameterEasingFloatCore value) {
    GDXJNI.RingSingleParameterCore_easing_set(swigCPtr, this, ParameterEasingFloatCore.getCPtr(value), value);
  }

  public ParameterEasingFloatCore getEasing() {
    long cPtr = GDXJNI.RingSingleParameterCore_easing_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ParameterEasingFloatCore(cPtr, false);
  }

  public RingSingleParameterCore() {
    this(GDXJNI.new_RingSingleParameterCore(), true);
  }

  public final static int Fixed = GDXJNI.RingSingleParameterCore_Fixed_get();
  public final static int Random = GDXJNI.RingSingleParameterCore_Random_get();
  public final static int Easing = GDXJNI.RingSingleParameterCore_Easing_get();
  public final static int Parameter_DWORD = GDXJNI.RingSingleParameterCore_Parameter_DWORD_get();

}
