/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class RingShapeParameterCore {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RingShapeParameterCore(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RingShapeParameterCore obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_RingShapeParameterCore(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(RingShapeType value) {
    GDXJNI.RingShapeParameterCore_Type_set(swigCPtr, this, value.swigValue());
  }

  public RingShapeType getType() {
    return RingShapeType.swigToEnum(GDXJNI.RingShapeParameterCore_Type_get(swigCPtr, this));
  }

  public void setStartingFade(float value) {
    GDXJNI.RingShapeParameterCore_StartingFade_set(swigCPtr, this, value);
  }

  public float getStartingFade() {
    return GDXJNI.RingShapeParameterCore_StartingFade_get(swigCPtr, this);
  }

  public void setEndingFade(float value) {
    GDXJNI.RingShapeParameterCore_EndingFade_set(swigCPtr, this, value);
  }

  public float getEndingFade() {
    return GDXJNI.RingShapeParameterCore_EndingFade_get(swigCPtr, this);
  }

  public void setStartingAngle(RingSingleParameterCore value) {
    GDXJNI.RingShapeParameterCore_StartingAngle_set(swigCPtr, this, RingSingleParameterCore.getCPtr(value), value);
  }

  public RingSingleParameterCore getStartingAngle() {
    long cPtr = GDXJNI.RingShapeParameterCore_StartingAngle_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RingSingleParameterCore(cPtr, false);
  }

  public void setEndingAngle(RingSingleParameterCore value) {
    GDXJNI.RingShapeParameterCore_EndingAngle_set(swigCPtr, this, RingSingleParameterCore.getCPtr(value), value);
  }

  public RingSingleParameterCore getEndingAngle() {
    long cPtr = GDXJNI.RingShapeParameterCore_EndingAngle_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RingSingleParameterCore(cPtr, false);
  }

  public RingShapeParameterCore() {
    this(GDXJNI.new_RingShapeParameterCore(), true);
  }

}
