/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class RingColorParameterCore {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RingColorParameterCore(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RingColorParameterCore obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_RingColorParameterCore(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(int value) {
    GDXJNI.RingColorParameterCore_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return GDXJNI.RingColorParameterCore_type_get(swigCPtr, this);
  }

  public void setFixed(Color value) {
    GDXJNI.RingColorParameterCore_fixed_set(swigCPtr, this, Color.getCPtr(value), value);
  }

  public Color getFixed() {
    long cPtr = GDXJNI.RingColorParameterCore_fixed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Color(cPtr, false);
  }

  public void setRandom(InternalStructRandomColor value) {
    GDXJNI.RingColorParameterCore_random_set(swigCPtr, this, InternalStructRandomColor.getCPtr(value), value);
  }

  public InternalStructRandomColor getRandom() {
    long cPtr = GDXJNI.RingColorParameterCore_random_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InternalStructRandomColor(cPtr, false);
  }

  public void setEasing(InternalStructEasingColor value) {
    GDXJNI.RingColorParameterCore_easing_set(swigCPtr, this, InternalStructEasingColor.getCPtr(value), value);
  }

  public InternalStructEasingColor getEasing() {
    long cPtr = GDXJNI.RingColorParameterCore_easing_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InternalStructEasingColor(cPtr, false);
  }

  public RingColorParameterCore() {
    this(GDXJNI.new_RingColorParameterCore(), true);
  }

  public final static int Fixed = GDXJNI.RingColorParameterCore_Fixed_get();
  public final static int Random = GDXJNI.RingColorParameterCore_Random_get();
  public final static int Easing = GDXJNI.RingColorParameterCore_Easing_get();
  public final static int Parameter_DWORD = GDXJNI.RingColorParameterCore_Parameter_DWORD_get();

}
