/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class SIMDVec3f {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SIMDVec3f(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SIMDVec3f obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_SIMDVec3f(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SIMDVec3f() {
    this(GDXJNI.new_SIMDVec3f__SWIG_0(), true);
  }

  public SIMDVec3f(SIMDVec3f vec) {
    this(GDXJNI.new_SIMDVec3f__SWIG_1(SIMDVec3f.getCPtr(vec), vec), true);
  }

  public SIMDVec3f(float x, float y, float z) {
    this(GDXJNI.new_SIMDVec3f__SWIG_2(x, y, z), true);
  }

  public SIMDVec3f(Vector3D vec) {
    this(GDXJNI.new_SIMDVec3f__SWIG_3(Vector3D.getCPtr(vec), vec), true);
  }

  public SIMDVec3f(InternalStructVector3D vec) {
    this(GDXJNI.new_SIMDVec3f__SWIG_4(InternalStructVector3D.getCPtr(vec), vec), true);
  }

  public float GetX() {
    return GDXJNI.SIMDVec3f_GetX(swigCPtr, this);
  }

  public float GetY() {
    return GDXJNI.SIMDVec3f_GetY(swigCPtr, this);
  }

  public float GetZ() {
    return GDXJNI.SIMDVec3f_GetZ(swigCPtr, this);
  }

  public void SetX(float o) {
    GDXJNI.SIMDVec3f_SetX(swigCPtr, this, o);
  }

  public void SetY(float o) {
    GDXJNI.SIMDVec3f_SetY(swigCPtr, this, o);
  }

  public void SetZ(float o) {
    GDXJNI.SIMDVec3f_SetZ(swigCPtr, this, o);
  }

}
