/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class SIMDMat44f {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SIMDMat44f(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SIMDMat44f obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_SIMDMat44f(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SIMDMat44f() {
    this(GDXJNI.new_SIMDMat44f__SWIG_0(), true);
  }

  public SIMDMat44f(SIMDMat44f rhs) {
    this(GDXJNI.new_SIMDMat44f__SWIG_1(SIMDMat44f.getCPtr(rhs), rhs), true);
  }

  public SIMDMat44f(float m11, float m12, float m13, float m14, float m21, float m22, float m23, float m24, float m31, float m32, float m33, float m34, float m41, float m42, float m43, float m44) {
    this(GDXJNI.new_SIMDMat44f__SWIG_2(m11, m12, m13, m14, m21, m22, m23, m24, m31, m32, m33, m34, m41, m42, m43, m44), true);
  }

  public SIMDMat44f(SIMDMat43f mat) {
    this(GDXJNI.new_SIMDMat44f__SWIG_3(SIMDMat43f.getCPtr(mat), mat), true);
  }

  public SIMDMat44f(Matrix44 mat) {
    this(GDXJNI.new_SIMDMat44f__SWIG_4(Matrix44.getCPtr(mat), mat), true);
  }

  public static SIMDMat44f getIdentity() {
    long cPtr = GDXJNI.SIMDMat44f_Identity_get();
    return (cPtr == 0) ? null : new SIMDMat44f(cPtr, false);
  }

}
