/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class SIMDMat43f {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SIMDMat43f(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SIMDMat43f obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GDXJNI.delete_SIMDMat43f(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SIMDMat43f() {
    this(GDXJNI.new_SIMDMat43f__SWIG_0(), true);
  }

  public SIMDMat43f(SIMDMat43f rhs) {
    this(GDXJNI.new_SIMDMat43f__SWIG_1(SIMDMat43f.getCPtr(rhs), rhs), true);
  }

  public SIMDMat43f(float m11, float m12, float m13, float m21, float m22, float m23, float m31, float m32, float m33, float m41, float m42, float m43) {
    this(GDXJNI.new_SIMDMat43f__SWIG_2(m11, m12, m13, m21, m22, m23, m31, m32, m33, m41, m42, m43), true);
  }

  public SIMDMat43f(Matrix43 mat) {
    this(GDXJNI.new_SIMDMat43f__SWIG_3(Matrix43.getCPtr(mat), mat), true);
  }

  public static SIMDMat43f getIdentity() {
    long cPtr = GDXJNI.SIMDMat43f_Identity_get();
    return (cPtr == 0) ? null : new SIMDMat43f(cPtr, false);
  }

}
