/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public class SWIGTYPE_p_a_3__float {
  private transient long swigCPtr;

  protected SWIGTYPE_p_a_3__float(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_a_3__float() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_a_3__float obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

