/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public final class TextureType {
  public final static TextureType Color = new TextureType("Color");
  public final static TextureType Normal = new TextureType("Normal");
  public final static TextureType Distortion = new TextureType("Distortion");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TextureType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TextureType.class + " with value " + swigValue);
  }

  private TextureType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TextureType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TextureType(String swigName, TextureType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TextureType[] swigValues = { Color, Normal, Distortion };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

