/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.srjohnathan.gdx.effekseer.core;

public final class TextureWrapType {
  public final static TextureWrapType Repeat = new TextureWrapType("Repeat", GDXJNI.TextureWrapType_Repeat_get());
  public final static TextureWrapType Clamp = new TextureWrapType("Clamp", GDXJNI.TextureWrapType_Clamp_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TextureWrapType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TextureWrapType.class + " with value " + swigValue);
  }

  private TextureWrapType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TextureWrapType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TextureWrapType(String swigName, TextureWrapType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TextureWrapType[] swigValues = { Repeat, Clamp };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

